# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-19 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='year of start time,is negative when BC,-238 means 238 BC')),
                ('month', models.IntegerField(default=0, help_text='month of start time,1~12')),
                ('day', models.IntegerField(default=0, help_text='day of start time,1~31')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('abstract', models.CharField(max_length=3000)),
                ('timestamp', models.IntegerField(help_text='s*(year*10000+month*100+day),s is -1 means BC,20180103=2018 AD/01/13,-3390413=339 BC/04/13')),
                ('year2', models.IntegerField(blank=True, help_text='year of end time if existed,is negative when BC,-238 means 238 BC', null=True)),
                ('month2', models.IntegerField(blank=True, default=0, help_text='month of end time if existed,1~12')),
                ('day2', models.IntegerField(blank=True, default=0, help_text='day of end time if existed,1~31')),
                ('timestamp2', models.IntegerField(help_text='s*(year2*10000+month2*100+day2),s is -1 means BC,20180103=2018 AD/01/13,-3390413=339 BC/04/13', null=True)),
                ('online_url', models.URLField(blank=True, help_text='Online resource html', max_length=3000, null=True)),
                ('public_status', models.BooleanField(default=False, help_text='Is public')),
                ('level', models.SmallIntegerField(choices=[(1, '\u6781\u5176\u91cd\u8981\u7684\u4e8b\u4ef6'), (2, '\u5173\u952e\u7684\u4e8b\u4ef6'), (3, '\u8fc7\u6e21\u6027\u4e8b\u4ef6')], default=3)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='event.Tag'),
        ),
    ]
