# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='year,is negative when BC,-238 means 238 BC')),
                ('month', models.IntegerField(help_text='month,1~12')),
                ('day', models.IntegerField(help_text='day,1~31')),
                ('title', models.CharField(max_length=128)),
                ('abstract', models.CharField(max_length=256)),
                ('timestamp', models.IntegerField(help_text='s*(year*10000+month*100+day),s is -1 means BC,20180103=2018 AD/01/13,-3390413=339 BC/04/13')),
            ],
        ),
    ]
