# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180104_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='abstract',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.IntegerField(default=0, help_text='day of start time,1~31'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day2',
            field=models.IntegerField(blank=True, help_text='day of end time if existed,1~31', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.IntegerField(default=0, help_text='month of start time,1~12'),
        ),
        migrations.AlterField(
            model_name='event',
            name='month2',
            field=models.IntegerField(blank=True, help_text='month of end time if existed,1~12', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='year2',
            field=models.IntegerField(blank=True, help_text='year of end time if existed,is negative when BC,-238 means 238 BC', null=True),
        ),
    ]
