# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180111_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_url',
            field=models.CharField(blank=True, help_text='Online resource html', max_length=3000, null=True),
        ),
    ]
