# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180111_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
