# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20180111_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_status',
            field=models.BooleanField(default=False, help_text='Is public'),
        ),
    ]
