# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_public_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '\u6781\u5176\u91cd\u8981\u7684\u4e8b\u4ef6\uff0c\u51e0\u5927\u6587\u660e\u7684\u738b\u671d\u66f4\u8fed\uff0c\u91cd\u8981\u4eba\u7269\u4e3b\u5bfc\u7684\u4e8b\u4ef6\u4ee5\u53ca\u6b7b\u4ea1'), (2, '\u5173\u952e\u7684\u4e8b\u4ef6\uff0c\u7b2c\u4e00\u7c7b\u4e8b\u4ef6\u7684\u5173\u952e\u70b9\uff0c\u91cd\u5927\u6539\u9769\u6216\u9769\u547d\uff0c\u91cd\u8981\u4eba\u7269\u7684\u51fa\u4e8b'), (3, '\u5173\u952e\u7684\u4e8b\u4ef6\uff0c\u7b2c\u4e8c\u7c7b\u4e8b\u4ef6\u7684\u5173\u952e\u70b9\uff0c\u8fc7\u6e21\u6027\u4e8b\u4ef6')], default=3, max_length=2),
        ),
    ]
