# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20180117_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '\u6781\u5176\u91cd\u8981\u7684\u4e8b\u4ef6'), (2, '\u5173\u952e\u7684\u4e8b\u4ef6'), (3, '\u8fc7\u6e21\u6027\u4e8b\u4ef6')], default=3),
        ),
    ]
