# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20180202_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtag',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventtag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='EventTag',
        ),
    ]
