# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20180202_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timestamp2',
            field=models.IntegerField(help_text='s*(year2*10000+month2*100+day2),s is -1 means BC,20180103=2018 AD/01/13,-3390413=339 BC/04/13', null=True),
        ),
    ]
