# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-18 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_event_timestamp2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day2',
            field=models.IntegerField(blank=True, default=0, help_text='day of end time if existed,1~31'),
        ),
        migrations.AlterField(
            model_name='event',
            name='month2',
            field=models.IntegerField(blank=True, default=0, help_text='month of end time if existed,1~12'),
        ),
    ]
