language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - cd adminsite
  - python manage.py test
after_success:
  - fab -u travis -p $TRAVIS_PASSWORD -H $DEPLOY_TARGET_HOSTS deploy
  - cd ..
  - ./startup.sh