language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - cd adminsite
  - python manage.py collectstatic -v0 --noinput
  - python manage.py makemigrations
  - python manage.py migrate
#  - python manage.py test
after_success:
  - fab -u travis -p $TRAVIS_PASSWORD -H $DEPLOY_TARGET_HOSTS deploy
notifications:
  email:
    recipients:
      - sillyemperor@qq.com
    on_success: always # default: change
    on_failure: always # default: always